### ISSUE TITLE
Archictecture.bin Missing & BAD_COOKIE

### ISSUE THREAD

**Issue by MC189** [9hk/googleplay#4]
# Background
Downloading apps will always result in:
```
panic: open C:\Users\Administrator/googleplay/[architecture].bin: The system cannot find the file specified.
```
I guess it's not generating ```[architecture].bin``` files properly. Even trying with passing other Architecture from ```-p``` parameter.

# Step to Reproduce
```
git clone https://github.com/9hk/googleplay
cd googleplay/cmd/googleplay
go build
./googleplay -email <Email> -password <Password> -device
./googleplay -a com.google.android.youtube
```
# Other Issue
Generating ```auth.txt``` using ```-device``` parameter left with ```SID``` and ```LSID``` with ```BAD_COOKIE```
```
SID=BAD_COOKIE
LSID=BAD_COOKIE
```
Is this supposed to be like that? Or is it related to ```BadAuthentication``` that most GPAPI Suffers?

# Attachment
Also tried in Windows Environment, still got the ```Panic```:
[The system cannot find the file specified.](https://user-images.githubusercontent.com/62210133/204183759-36fca3aa-6b42-4fb4-90fd-20c4cc198d35.png)

**Comment by 9hk** [comment]
https://github.com/9hk/googleplay#money
